/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.19.4
 * source: google/api/annotations.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
export declare namespace google.api { }
