/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.6.1
 * source: cosmos/distribution/v1beta1/query.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./../../base/query/v1beta1/pagination";
import * as dependency_2 from "./../../../gogoproto/gogo";
import * as dependency_3 from "./../../../google/api/annotations";
import * as dependency_4 from "./../../base/v1beta1/coin";
import * as dependency_5 from "./distribution";
import * as pb_1 from "google-protobuf";
import * as grpc_1 from "@grpc/grpc-js";
export namespace cosmos.distribution.v1beta1 {
    export class QueryParamsRequest extends pb_1.Message {
        constructor(data?: any[] | {}) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], []);
            if (!Array.isArray(data) && typeof data == "object") { }
        }
        static fromObject(data: {}) {
            const message = new QueryParamsRequest({});
            return message;
        }
        toObject() {
            const data: {} = {};
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): QueryParamsRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new QueryParamsRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): QueryParamsRequest {
            return QueryParamsRequest.deserialize(bytes);
        }
    }
    export class QueryParamsResponse extends pb_1.Message {
        constructor(data?: any[] | {
            params?: dependency_5.cosmos.distribution.v1beta1.Params;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], []);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("params" in data && data.params != undefined) {
                    this.params = data.params;
                }
            }
        }
        get params() {
            return pb_1.Message.getWrapperField(this, dependency_5.cosmos.distribution.v1beta1.Params, 1) as dependency_5.cosmos.distribution.v1beta1.Params;
        }
        set params(value: dependency_5.cosmos.distribution.v1beta1.Params) {
            pb_1.Message.setWrapperField(this, 1, value);
        }
        static fromObject(data: {
            params?: ReturnType<typeof dependency_5.cosmos.distribution.v1beta1.Params.prototype.toObject>;
        }) {
            const message = new QueryParamsResponse({});
            if (data.params != null) {
                message.params = dependency_5.cosmos.distribution.v1beta1.Params.fromObject(data.params);
            }
            return message;
        }
        toObject() {
            const data: {
                params?: ReturnType<typeof dependency_5.cosmos.distribution.v1beta1.Params.prototype.toObject>;
            } = {};
            if (this.params != null) {
                data.params = this.params.toObject();
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.params !== undefined)
                writer.writeMessage(1, this.params, () => this.params.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): QueryParamsResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new QueryParamsResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        reader.readMessage(message.params, () => message.params = dependency_5.cosmos.distribution.v1beta1.Params.deserialize(reader));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): QueryParamsResponse {
            return QueryParamsResponse.deserialize(bytes);
        }
    }
    export class QueryValidatorOutstandingRewardsRequest extends pb_1.Message {
        constructor(data?: any[] | {
            validator_address?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], []);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("validator_address" in data && data.validator_address != undefined) {
                    this.validator_address = data.validator_address;
                }
            }
        }
        get validator_address() {
            return pb_1.Message.getField(this, 1) as string;
        }
        set validator_address(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data: {
            validator_address?: string;
        }) {
            const message = new QueryValidatorOutstandingRewardsRequest({});
            if (data.validator_address != null) {
                message.validator_address = data.validator_address;
            }
            return message;
        }
        toObject() {
            const data: {
                validator_address?: string;
            } = {};
            if (this.validator_address != null) {
                data.validator_address = this.validator_address;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (typeof this.validator_address === "string" && this.validator_address.length)
                writer.writeString(1, this.validator_address);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): QueryValidatorOutstandingRewardsRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new QueryValidatorOutstandingRewardsRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.validator_address = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): QueryValidatorOutstandingRewardsRequest {
            return QueryValidatorOutstandingRewardsRequest.deserialize(bytes);
        }
    }
    export class QueryValidatorOutstandingRewardsResponse extends pb_1.Message {
        constructor(data?: any[] | {
            rewards?: dependency_5.cosmos.distribution.v1beta1.ValidatorOutstandingRewards;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], []);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("rewards" in data && data.rewards != undefined) {
                    this.rewards = data.rewards;
                }
            }
        }
        get rewards() {
            return pb_1.Message.getWrapperField(this, dependency_5.cosmos.distribution.v1beta1.ValidatorOutstandingRewards, 1) as dependency_5.cosmos.distribution.v1beta1.ValidatorOutstandingRewards;
        }
        set rewards(value: dependency_5.cosmos.distribution.v1beta1.ValidatorOutstandingRewards) {
            pb_1.Message.setWrapperField(this, 1, value);
        }
        static fromObject(data: {
            rewards?: ReturnType<typeof dependency_5.cosmos.distribution.v1beta1.ValidatorOutstandingRewards.prototype.toObject>;
        }) {
            const message = new QueryValidatorOutstandingRewardsResponse({});
            if (data.rewards != null) {
                message.rewards = dependency_5.cosmos.distribution.v1beta1.ValidatorOutstandingRewards.fromObject(data.rewards);
            }
            return message;
        }
        toObject() {
            const data: {
                rewards?: ReturnType<typeof dependency_5.cosmos.distribution.v1beta1.ValidatorOutstandingRewards.prototype.toObject>;
            } = {};
            if (this.rewards != null) {
                data.rewards = this.rewards.toObject();
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.rewards !== undefined)
                writer.writeMessage(1, this.rewards, () => this.rewards.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): QueryValidatorOutstandingRewardsResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new QueryValidatorOutstandingRewardsResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        reader.readMessage(message.rewards, () => message.rewards = dependency_5.cosmos.distribution.v1beta1.ValidatorOutstandingRewards.deserialize(reader));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): QueryValidatorOutstandingRewardsResponse {
            return QueryValidatorOutstandingRewardsResponse.deserialize(bytes);
        }
    }
    export class QueryValidatorCommissionRequest extends pb_1.Message {
        constructor(data?: any[] | {
            validator_address?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], []);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("validator_address" in data && data.validator_address != undefined) {
                    this.validator_address = data.validator_address;
                }
            }
        }
        get validator_address() {
            return pb_1.Message.getField(this, 1) as string;
        }
        set validator_address(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data: {
            validator_address?: string;
        }) {
            const message = new QueryValidatorCommissionRequest({});
            if (data.validator_address != null) {
                message.validator_address = data.validator_address;
            }
            return message;
        }
        toObject() {
            const data: {
                validator_address?: string;
            } = {};
            if (this.validator_address != null) {
                data.validator_address = this.validator_address;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (typeof this.validator_address === "string" && this.validator_address.length)
                writer.writeString(1, this.validator_address);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): QueryValidatorCommissionRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new QueryValidatorCommissionRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.validator_address = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): QueryValidatorCommissionRequest {
            return QueryValidatorCommissionRequest.deserialize(bytes);
        }
    }
    export class QueryValidatorCommissionResponse extends pb_1.Message {
        constructor(data?: any[] | {
            commission?: dependency_5.cosmos.distribution.v1beta1.ValidatorAccumulatedCommission;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], []);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("commission" in data && data.commission != undefined) {
                    this.commission = data.commission;
                }
            }
        }
        get commission() {
            return pb_1.Message.getWrapperField(this, dependency_5.cosmos.distribution.v1beta1.ValidatorAccumulatedCommission, 1) as dependency_5.cosmos.distribution.v1beta1.ValidatorAccumulatedCommission;
        }
        set commission(value: dependency_5.cosmos.distribution.v1beta1.ValidatorAccumulatedCommission) {
            pb_1.Message.setWrapperField(this, 1, value);
        }
        static fromObject(data: {
            commission?: ReturnType<typeof dependency_5.cosmos.distribution.v1beta1.ValidatorAccumulatedCommission.prototype.toObject>;
        }) {
            const message = new QueryValidatorCommissionResponse({});
            if (data.commission != null) {
                message.commission = dependency_5.cosmos.distribution.v1beta1.ValidatorAccumulatedCommission.fromObject(data.commission);
            }
            return message;
        }
        toObject() {
            const data: {
                commission?: ReturnType<typeof dependency_5.cosmos.distribution.v1beta1.ValidatorAccumulatedCommission.prototype.toObject>;
            } = {};
            if (this.commission != null) {
                data.commission = this.commission.toObject();
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.commission !== undefined)
                writer.writeMessage(1, this.commission, () => this.commission.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): QueryValidatorCommissionResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new QueryValidatorCommissionResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        reader.readMessage(message.commission, () => message.commission = dependency_5.cosmos.distribution.v1beta1.ValidatorAccumulatedCommission.deserialize(reader));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): QueryValidatorCommissionResponse {
            return QueryValidatorCommissionResponse.deserialize(bytes);
        }
    }
    export class QueryValidatorSlashesRequest extends pb_1.Message {
        constructor(data?: any[] | {
            validator_address?: string;
            starting_height?: number;
            ending_height?: number;
            pagination?: dependency_1.cosmos.base.query.v1beta1.PageRequest;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], []);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("validator_address" in data && data.validator_address != undefined) {
                    this.validator_address = data.validator_address;
                }
                if ("starting_height" in data && data.starting_height != undefined) {
                    this.starting_height = data.starting_height;
                }
                if ("ending_height" in data && data.ending_height != undefined) {
                    this.ending_height = data.ending_height;
                }
                if ("pagination" in data && data.pagination != undefined) {
                    this.pagination = data.pagination;
                }
            }
        }
        get validator_address() {
            return pb_1.Message.getField(this, 1) as string;
        }
        set validator_address(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get starting_height() {
            return pb_1.Message.getField(this, 2) as number;
        }
        set starting_height(value: number) {
            pb_1.Message.setField(this, 2, value);
        }
        get ending_height() {
            return pb_1.Message.getField(this, 3) as number;
        }
        set ending_height(value: number) {
            pb_1.Message.setField(this, 3, value);
        }
        get pagination() {
            return pb_1.Message.getWrapperField(this, dependency_1.cosmos.base.query.v1beta1.PageRequest, 4) as dependency_1.cosmos.base.query.v1beta1.PageRequest;
        }
        set pagination(value: dependency_1.cosmos.base.query.v1beta1.PageRequest) {
            pb_1.Message.setWrapperField(this, 4, value);
        }
        static fromObject(data: {
            validator_address?: string;
            starting_height?: number;
            ending_height?: number;
            pagination?: ReturnType<typeof dependency_1.cosmos.base.query.v1beta1.PageRequest.prototype.toObject>;
        }) {
            const message = new QueryValidatorSlashesRequest({});
            if (data.validator_address != null) {
                message.validator_address = data.validator_address;
            }
            if (data.starting_height != null) {
                message.starting_height = data.starting_height;
            }
            if (data.ending_height != null) {
                message.ending_height = data.ending_height;
            }
            if (data.pagination != null) {
                message.pagination = dependency_1.cosmos.base.query.v1beta1.PageRequest.fromObject(data.pagination);
            }
            return message;
        }
        toObject() {
            const data: {
                validator_address?: string;
                starting_height?: number;
                ending_height?: number;
                pagination?: ReturnType<typeof dependency_1.cosmos.base.query.v1beta1.PageRequest.prototype.toObject>;
            } = {};
            if (this.validator_address != null) {
                data.validator_address = this.validator_address;
            }
            if (this.starting_height != null) {
                data.starting_height = this.starting_height;
            }
            if (this.ending_height != null) {
                data.ending_height = this.ending_height;
            }
            if (this.pagination != null) {
                data.pagination = this.pagination.toObject();
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (typeof this.validator_address === "string" && this.validator_address.length)
                writer.writeString(1, this.validator_address);
            if (this.starting_height !== undefined)
                writer.writeUint64(2, this.starting_height);
            if (this.ending_height !== undefined)
                writer.writeUint64(3, this.ending_height);
            if (this.pagination !== undefined)
                writer.writeMessage(4, this.pagination, () => this.pagination.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): QueryValidatorSlashesRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new QueryValidatorSlashesRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.validator_address = reader.readString();
                        break;
                    case 2:
                        message.starting_height = reader.readUint64();
                        break;
                    case 3:
                        message.ending_height = reader.readUint64();
                        break;
                    case 4:
                        reader.readMessage(message.pagination, () => message.pagination = dependency_1.cosmos.base.query.v1beta1.PageRequest.deserialize(reader));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): QueryValidatorSlashesRequest {
            return QueryValidatorSlashesRequest.deserialize(bytes);
        }
    }
    export class QueryValidatorSlashesResponse extends pb_1.Message {
        constructor(data?: any[] | {
            slashes?: dependency_5.cosmos.distribution.v1beta1.ValidatorSlashEvent[];
            pagination?: dependency_1.cosmos.base.query.v1beta1.PageResponse;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [1], []);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("slashes" in data && data.slashes != undefined) {
                    this.slashes = data.slashes;
                }
                if ("pagination" in data && data.pagination != undefined) {
                    this.pagination = data.pagination;
                }
            }
        }
        get slashes() {
            return pb_1.Message.getRepeatedWrapperField(this, dependency_5.cosmos.distribution.v1beta1.ValidatorSlashEvent, 1) as dependency_5.cosmos.distribution.v1beta1.ValidatorSlashEvent[];
        }
        set slashes(value: dependency_5.cosmos.distribution.v1beta1.ValidatorSlashEvent[]) {
            pb_1.Message.setRepeatedWrapperField(this, 1, value);
        }
        get pagination() {
            return pb_1.Message.getWrapperField(this, dependency_1.cosmos.base.query.v1beta1.PageResponse, 2) as dependency_1.cosmos.base.query.v1beta1.PageResponse;
        }
        set pagination(value: dependency_1.cosmos.base.query.v1beta1.PageResponse) {
            pb_1.Message.setWrapperField(this, 2, value);
        }
        static fromObject(data: {
            slashes?: ReturnType<typeof dependency_5.cosmos.distribution.v1beta1.ValidatorSlashEvent.prototype.toObject>[];
            pagination?: ReturnType<typeof dependency_1.cosmos.base.query.v1beta1.PageResponse.prototype.toObject>;
        }) {
            const message = new QueryValidatorSlashesResponse({});
            if (data.slashes != null) {
                message.slashes = data.slashes.map(item => dependency_5.cosmos.distribution.v1beta1.ValidatorSlashEvent.fromObject(item));
            }
            if (data.pagination != null) {
                message.pagination = dependency_1.cosmos.base.query.v1beta1.PageResponse.fromObject(data.pagination);
            }
            return message;
        }
        toObject() {
            const data: {
                slashes?: ReturnType<typeof dependency_5.cosmos.distribution.v1beta1.ValidatorSlashEvent.prototype.toObject>[];
                pagination?: ReturnType<typeof dependency_1.cosmos.base.query.v1beta1.PageResponse.prototype.toObject>;
            } = {};
            if (this.slashes != null) {
                data.slashes = this.slashes.map((item: dependency_5.cosmos.distribution.v1beta1.ValidatorSlashEvent) => item.toObject());
            }
            if (this.pagination != null) {
                data.pagination = this.pagination.toObject();
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.slashes !== undefined)
                writer.writeRepeatedMessage(1, this.slashes, (item: dependency_5.cosmos.distribution.v1beta1.ValidatorSlashEvent) => item.serialize(writer));
            if (this.pagination !== undefined)
                writer.writeMessage(2, this.pagination, () => this.pagination.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): QueryValidatorSlashesResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new QueryValidatorSlashesResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        reader.readMessage(message.slashes, () => pb_1.Message.addToRepeatedWrapperField(message, 1, dependency_5.cosmos.distribution.v1beta1.ValidatorSlashEvent.deserialize(reader), dependency_5.cosmos.distribution.v1beta1.ValidatorSlashEvent));
                        break;
                    case 2:
                        reader.readMessage(message.pagination, () => message.pagination = dependency_1.cosmos.base.query.v1beta1.PageResponse.deserialize(reader));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): QueryValidatorSlashesResponse {
            return QueryValidatorSlashesResponse.deserialize(bytes);
        }
    }
    export class QueryDelegationRewardsRequest extends pb_1.Message {
        constructor(data?: any[] | {
            delegator_address?: string;
            validator_address?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], []);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("delegator_address" in data && data.delegator_address != undefined) {
                    this.delegator_address = data.delegator_address;
                }
                if ("validator_address" in data && data.validator_address != undefined) {
                    this.validator_address = data.validator_address;
                }
            }
        }
        get delegator_address() {
            return pb_1.Message.getField(this, 1) as string;
        }
        set delegator_address(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get validator_address() {
            return pb_1.Message.getField(this, 2) as string;
        }
        set validator_address(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        static fromObject(data: {
            delegator_address?: string;
            validator_address?: string;
        }) {
            const message = new QueryDelegationRewardsRequest({});
            if (data.delegator_address != null) {
                message.delegator_address = data.delegator_address;
            }
            if (data.validator_address != null) {
                message.validator_address = data.validator_address;
            }
            return message;
        }
        toObject() {
            const data: {
                delegator_address?: string;
                validator_address?: string;
            } = {};
            if (this.delegator_address != null) {
                data.delegator_address = this.delegator_address;
            }
            if (this.validator_address != null) {
                data.validator_address = this.validator_address;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (typeof this.delegator_address === "string" && this.delegator_address.length)
                writer.writeString(1, this.delegator_address);
            if (typeof this.validator_address === "string" && this.validator_address.length)
                writer.writeString(2, this.validator_address);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): QueryDelegationRewardsRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new QueryDelegationRewardsRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.delegator_address = reader.readString();
                        break;
                    case 2:
                        message.validator_address = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): QueryDelegationRewardsRequest {
            return QueryDelegationRewardsRequest.deserialize(bytes);
        }
    }
    export class QueryDelegationRewardsResponse extends pb_1.Message {
        constructor(data?: any[] | {
            rewards?: dependency_4.cosmos.base.v1beta1.DecCoin[];
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [1], []);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("rewards" in data && data.rewards != undefined) {
                    this.rewards = data.rewards;
                }
            }
        }
        get rewards() {
            return pb_1.Message.getRepeatedWrapperField(this, dependency_4.cosmos.base.v1beta1.DecCoin, 1) as dependency_4.cosmos.base.v1beta1.DecCoin[];
        }
        set rewards(value: dependency_4.cosmos.base.v1beta1.DecCoin[]) {
            pb_1.Message.setRepeatedWrapperField(this, 1, value);
        }
        static fromObject(data: {
            rewards?: ReturnType<typeof dependency_4.cosmos.base.v1beta1.DecCoin.prototype.toObject>[];
        }) {
            const message = new QueryDelegationRewardsResponse({});
            if (data.rewards != null) {
                message.rewards = data.rewards.map(item => dependency_4.cosmos.base.v1beta1.DecCoin.fromObject(item));
            }
            return message;
        }
        toObject() {
            const data: {
                rewards?: ReturnType<typeof dependency_4.cosmos.base.v1beta1.DecCoin.prototype.toObject>[];
            } = {};
            if (this.rewards != null) {
                data.rewards = this.rewards.map((item: dependency_4.cosmos.base.v1beta1.DecCoin) => item.toObject());
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.rewards !== undefined)
                writer.writeRepeatedMessage(1, this.rewards, (item: dependency_4.cosmos.base.v1beta1.DecCoin) => item.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): QueryDelegationRewardsResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new QueryDelegationRewardsResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        reader.readMessage(message.rewards, () => pb_1.Message.addToRepeatedWrapperField(message, 1, dependency_4.cosmos.base.v1beta1.DecCoin.deserialize(reader), dependency_4.cosmos.base.v1beta1.DecCoin));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): QueryDelegationRewardsResponse {
            return QueryDelegationRewardsResponse.deserialize(bytes);
        }
    }
    export class QueryDelegationTotalRewardsRequest extends pb_1.Message {
        constructor(data?: any[] | {
            delegator_address?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], []);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("delegator_address" in data && data.delegator_address != undefined) {
                    this.delegator_address = data.delegator_address;
                }
            }
        }
        get delegator_address() {
            return pb_1.Message.getField(this, 1) as string;
        }
        set delegator_address(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data: {
            delegator_address?: string;
        }) {
            const message = new QueryDelegationTotalRewardsRequest({});
            if (data.delegator_address != null) {
                message.delegator_address = data.delegator_address;
            }
            return message;
        }
        toObject() {
            const data: {
                delegator_address?: string;
            } = {};
            if (this.delegator_address != null) {
                data.delegator_address = this.delegator_address;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (typeof this.delegator_address === "string" && this.delegator_address.length)
                writer.writeString(1, this.delegator_address);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): QueryDelegationTotalRewardsRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new QueryDelegationTotalRewardsRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.delegator_address = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): QueryDelegationTotalRewardsRequest {
            return QueryDelegationTotalRewardsRequest.deserialize(bytes);
        }
    }
    export class QueryDelegationTotalRewardsResponse extends pb_1.Message {
        constructor(data?: any[] | {
            rewards?: dependency_5.cosmos.distribution.v1beta1.DelegationDelegatorReward[];
            total?: dependency_4.cosmos.base.v1beta1.DecCoin[];
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [1, 2], []);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("rewards" in data && data.rewards != undefined) {
                    this.rewards = data.rewards;
                }
                if ("total" in data && data.total != undefined) {
                    this.total = data.total;
                }
            }
        }
        get rewards() {
            return pb_1.Message.getRepeatedWrapperField(this, dependency_5.cosmos.distribution.v1beta1.DelegationDelegatorReward, 1) as dependency_5.cosmos.distribution.v1beta1.DelegationDelegatorReward[];
        }
        set rewards(value: dependency_5.cosmos.distribution.v1beta1.DelegationDelegatorReward[]) {
            pb_1.Message.setRepeatedWrapperField(this, 1, value);
        }
        get total() {
            return pb_1.Message.getRepeatedWrapperField(this, dependency_4.cosmos.base.v1beta1.DecCoin, 2) as dependency_4.cosmos.base.v1beta1.DecCoin[];
        }
        set total(value: dependency_4.cosmos.base.v1beta1.DecCoin[]) {
            pb_1.Message.setRepeatedWrapperField(this, 2, value);
        }
        static fromObject(data: {
            rewards?: ReturnType<typeof dependency_5.cosmos.distribution.v1beta1.DelegationDelegatorReward.prototype.toObject>[];
            total?: ReturnType<typeof dependency_4.cosmos.base.v1beta1.DecCoin.prototype.toObject>[];
        }) {
            const message = new QueryDelegationTotalRewardsResponse({});
            if (data.rewards != null) {
                message.rewards = data.rewards.map(item => dependency_5.cosmos.distribution.v1beta1.DelegationDelegatorReward.fromObject(item));
            }
            if (data.total != null) {
                message.total = data.total.map(item => dependency_4.cosmos.base.v1beta1.DecCoin.fromObject(item));
            }
            return message;
        }
        toObject() {
            const data: {
                rewards?: ReturnType<typeof dependency_5.cosmos.distribution.v1beta1.DelegationDelegatorReward.prototype.toObject>[];
                total?: ReturnType<typeof dependency_4.cosmos.base.v1beta1.DecCoin.prototype.toObject>[];
            } = {};
            if (this.rewards != null) {
                data.rewards = this.rewards.map((item: dependency_5.cosmos.distribution.v1beta1.DelegationDelegatorReward) => item.toObject());
            }
            if (this.total != null) {
                data.total = this.total.map((item: dependency_4.cosmos.base.v1beta1.DecCoin) => item.toObject());
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.rewards !== undefined)
                writer.writeRepeatedMessage(1, this.rewards, (item: dependency_5.cosmos.distribution.v1beta1.DelegationDelegatorReward) => item.serialize(writer));
            if (this.total !== undefined)
                writer.writeRepeatedMessage(2, this.total, (item: dependency_4.cosmos.base.v1beta1.DecCoin) => item.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): QueryDelegationTotalRewardsResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new QueryDelegationTotalRewardsResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        reader.readMessage(message.rewards, () => pb_1.Message.addToRepeatedWrapperField(message, 1, dependency_5.cosmos.distribution.v1beta1.DelegationDelegatorReward.deserialize(reader), dependency_5.cosmos.distribution.v1beta1.DelegationDelegatorReward));
                        break;
                    case 2:
                        reader.readMessage(message.total, () => pb_1.Message.addToRepeatedWrapperField(message, 2, dependency_4.cosmos.base.v1beta1.DecCoin.deserialize(reader), dependency_4.cosmos.base.v1beta1.DecCoin));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): QueryDelegationTotalRewardsResponse {
            return QueryDelegationTotalRewardsResponse.deserialize(bytes);
        }
    }
    export class QueryDelegatorValidatorsRequest extends pb_1.Message {
        constructor(data?: any[] | {
            delegator_address?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], []);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("delegator_address" in data && data.delegator_address != undefined) {
                    this.delegator_address = data.delegator_address;
                }
            }
        }
        get delegator_address() {
            return pb_1.Message.getField(this, 1) as string;
        }
        set delegator_address(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data: {
            delegator_address?: string;
        }) {
            const message = new QueryDelegatorValidatorsRequest({});
            if (data.delegator_address != null) {
                message.delegator_address = data.delegator_address;
            }
            return message;
        }
        toObject() {
            const data: {
                delegator_address?: string;
            } = {};
            if (this.delegator_address != null) {
                data.delegator_address = this.delegator_address;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (typeof this.delegator_address === "string" && this.delegator_address.length)
                writer.writeString(1, this.delegator_address);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): QueryDelegatorValidatorsRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new QueryDelegatorValidatorsRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.delegator_address = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): QueryDelegatorValidatorsRequest {
            return QueryDelegatorValidatorsRequest.deserialize(bytes);
        }
    }
    export class QueryDelegatorValidatorsResponse extends pb_1.Message {
        constructor(data?: any[] | {
            validators?: string[];
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [1], []);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("validators" in data && data.validators != undefined) {
                    this.validators = data.validators;
                }
            }
        }
        get validators() {
            return pb_1.Message.getField(this, 1) as string[];
        }
        set validators(value: string[]) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data: {
            validators?: string[];
        }) {
            const message = new QueryDelegatorValidatorsResponse({});
            if (data.validators != null) {
                message.validators = data.validators;
            }
            return message;
        }
        toObject() {
            const data: {
                validators?: string[];
            } = {};
            if (this.validators != null) {
                data.validators = this.validators;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.validators !== undefined)
                writer.writeRepeatedString(1, this.validators);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): QueryDelegatorValidatorsResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new QueryDelegatorValidatorsResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        pb_1.Message.addToRepeatedField(message, 1, reader.readString());
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): QueryDelegatorValidatorsResponse {
            return QueryDelegatorValidatorsResponse.deserialize(bytes);
        }
    }
    export class QueryDelegatorWithdrawAddressRequest extends pb_1.Message {
        constructor(data?: any[] | {
            delegator_address?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], []);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("delegator_address" in data && data.delegator_address != undefined) {
                    this.delegator_address = data.delegator_address;
                }
            }
        }
        get delegator_address() {
            return pb_1.Message.getField(this, 1) as string;
        }
        set delegator_address(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data: {
            delegator_address?: string;
        }) {
            const message = new QueryDelegatorWithdrawAddressRequest({});
            if (data.delegator_address != null) {
                message.delegator_address = data.delegator_address;
            }
            return message;
        }
        toObject() {
            const data: {
                delegator_address?: string;
            } = {};
            if (this.delegator_address != null) {
                data.delegator_address = this.delegator_address;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (typeof this.delegator_address === "string" && this.delegator_address.length)
                writer.writeString(1, this.delegator_address);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): QueryDelegatorWithdrawAddressRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new QueryDelegatorWithdrawAddressRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.delegator_address = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): QueryDelegatorWithdrawAddressRequest {
            return QueryDelegatorWithdrawAddressRequest.deserialize(bytes);
        }
    }
    export class QueryDelegatorWithdrawAddressResponse extends pb_1.Message {
        constructor(data?: any[] | {
            withdraw_address?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], []);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("withdraw_address" in data && data.withdraw_address != undefined) {
                    this.withdraw_address = data.withdraw_address;
                }
            }
        }
        get withdraw_address() {
            return pb_1.Message.getField(this, 1) as string;
        }
        set withdraw_address(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data: {
            withdraw_address?: string;
        }) {
            const message = new QueryDelegatorWithdrawAddressResponse({});
            if (data.withdraw_address != null) {
                message.withdraw_address = data.withdraw_address;
            }
            return message;
        }
        toObject() {
            const data: {
                withdraw_address?: string;
            } = {};
            if (this.withdraw_address != null) {
                data.withdraw_address = this.withdraw_address;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (typeof this.withdraw_address === "string" && this.withdraw_address.length)
                writer.writeString(1, this.withdraw_address);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): QueryDelegatorWithdrawAddressResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new QueryDelegatorWithdrawAddressResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.withdraw_address = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): QueryDelegatorWithdrawAddressResponse {
            return QueryDelegatorWithdrawAddressResponse.deserialize(bytes);
        }
    }
    export class QueryCommunityPoolRequest extends pb_1.Message {
        constructor(data?: any[] | {}) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], []);
            if (!Array.isArray(data) && typeof data == "object") { }
        }
        static fromObject(data: {}) {
            const message = new QueryCommunityPoolRequest({});
            return message;
        }
        toObject() {
            const data: {} = {};
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): QueryCommunityPoolRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new QueryCommunityPoolRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): QueryCommunityPoolRequest {
            return QueryCommunityPoolRequest.deserialize(bytes);
        }
    }
    export class QueryCommunityPoolResponse extends pb_1.Message {
        constructor(data?: any[] | {
            pool?: dependency_4.cosmos.base.v1beta1.DecCoin[];
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [1], []);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("pool" in data && data.pool != undefined) {
                    this.pool = data.pool;
                }
            }
        }
        get pool() {
            return pb_1.Message.getRepeatedWrapperField(this, dependency_4.cosmos.base.v1beta1.DecCoin, 1) as dependency_4.cosmos.base.v1beta1.DecCoin[];
        }
        set pool(value: dependency_4.cosmos.base.v1beta1.DecCoin[]) {
            pb_1.Message.setRepeatedWrapperField(this, 1, value);
        }
        static fromObject(data: {
            pool?: ReturnType<typeof dependency_4.cosmos.base.v1beta1.DecCoin.prototype.toObject>[];
        }) {
            const message = new QueryCommunityPoolResponse({});
            if (data.pool != null) {
                message.pool = data.pool.map(item => dependency_4.cosmos.base.v1beta1.DecCoin.fromObject(item));
            }
            return message;
        }
        toObject() {
            const data: {
                pool?: ReturnType<typeof dependency_4.cosmos.base.v1beta1.DecCoin.prototype.toObject>[];
            } = {};
            if (this.pool != null) {
                data.pool = this.pool.map((item: dependency_4.cosmos.base.v1beta1.DecCoin) => item.toObject());
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.pool !== undefined)
                writer.writeRepeatedMessage(1, this.pool, (item: dependency_4.cosmos.base.v1beta1.DecCoin) => item.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): QueryCommunityPoolResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new QueryCommunityPoolResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        reader.readMessage(message.pool, () => pb_1.Message.addToRepeatedWrapperField(message, 1, dependency_4.cosmos.base.v1beta1.DecCoin.deserialize(reader), dependency_4.cosmos.base.v1beta1.DecCoin));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): QueryCommunityPoolResponse {
            return QueryCommunityPoolResponse.deserialize(bytes);
        }
    }
    interface GrpcUnaryServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
    }
    interface GrpcStreamServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
        (message: P, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
    }
    interface GrpWritableServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
    }
    interface GrpcChunkServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
        (options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
    }
    interface GrpcPromiseServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): Promise<R>;
        (message: P, options?: grpc_1.CallOptions): Promise<R>;
    }
    export abstract class UnimplementedQueryService {
        static definition = {
            Params: {
                path: "/cosmos.distribution.v1beta1.Query/Params",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: QueryParamsRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => QueryParamsRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: QueryParamsResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => QueryParamsResponse.deserialize(new Uint8Array(bytes))
            },
            ValidatorOutstandingRewards: {
                path: "/cosmos.distribution.v1beta1.Query/ValidatorOutstandingRewards",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: QueryValidatorOutstandingRewardsRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => QueryValidatorOutstandingRewardsRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: QueryValidatorOutstandingRewardsResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => QueryValidatorOutstandingRewardsResponse.deserialize(new Uint8Array(bytes))
            },
            ValidatorCommission: {
                path: "/cosmos.distribution.v1beta1.Query/ValidatorCommission",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: QueryValidatorCommissionRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => QueryValidatorCommissionRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: QueryValidatorCommissionResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => QueryValidatorCommissionResponse.deserialize(new Uint8Array(bytes))
            },
            ValidatorSlashes: {
                path: "/cosmos.distribution.v1beta1.Query/ValidatorSlashes",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: QueryValidatorSlashesRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => QueryValidatorSlashesRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: QueryValidatorSlashesResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => QueryValidatorSlashesResponse.deserialize(new Uint8Array(bytes))
            },
            DelegationRewards: {
                path: "/cosmos.distribution.v1beta1.Query/DelegationRewards",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: QueryDelegationRewardsRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => QueryDelegationRewardsRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: QueryDelegationRewardsResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => QueryDelegationRewardsResponse.deserialize(new Uint8Array(bytes))
            },
            DelegationTotalRewards: {
                path: "/cosmos.distribution.v1beta1.Query/DelegationTotalRewards",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: QueryDelegationTotalRewardsRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => QueryDelegationTotalRewardsRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: QueryDelegationTotalRewardsResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => QueryDelegationTotalRewardsResponse.deserialize(new Uint8Array(bytes))
            },
            DelegatorValidators: {
                path: "/cosmos.distribution.v1beta1.Query/DelegatorValidators",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: QueryDelegatorValidatorsRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => QueryDelegatorValidatorsRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: QueryDelegatorValidatorsResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => QueryDelegatorValidatorsResponse.deserialize(new Uint8Array(bytes))
            },
            DelegatorWithdrawAddress: {
                path: "/cosmos.distribution.v1beta1.Query/DelegatorWithdrawAddress",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: QueryDelegatorWithdrawAddressRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => QueryDelegatorWithdrawAddressRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: QueryDelegatorWithdrawAddressResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => QueryDelegatorWithdrawAddressResponse.deserialize(new Uint8Array(bytes))
            },
            CommunityPool: {
                path: "/cosmos.distribution.v1beta1.Query/CommunityPool",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: QueryCommunityPoolRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => QueryCommunityPoolRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: QueryCommunityPoolResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => QueryCommunityPoolResponse.deserialize(new Uint8Array(bytes))
            }
        };
        [method: string]: grpc_1.UntypedHandleCall;
        abstract Params(call: grpc_1.ServerUnaryCall<QueryParamsRequest, QueryParamsResponse>, callback: grpc_1.sendUnaryData<QueryParamsResponse>): void;
        abstract ValidatorOutstandingRewards(call: grpc_1.ServerUnaryCall<QueryValidatorOutstandingRewardsRequest, QueryValidatorOutstandingRewardsResponse>, callback: grpc_1.sendUnaryData<QueryValidatorOutstandingRewardsResponse>): void;
        abstract ValidatorCommission(call: grpc_1.ServerUnaryCall<QueryValidatorCommissionRequest, QueryValidatorCommissionResponse>, callback: grpc_1.sendUnaryData<QueryValidatorCommissionResponse>): void;
        abstract ValidatorSlashes(call: grpc_1.ServerUnaryCall<QueryValidatorSlashesRequest, QueryValidatorSlashesResponse>, callback: grpc_1.sendUnaryData<QueryValidatorSlashesResponse>): void;
        abstract DelegationRewards(call: grpc_1.ServerUnaryCall<QueryDelegationRewardsRequest, QueryDelegationRewardsResponse>, callback: grpc_1.sendUnaryData<QueryDelegationRewardsResponse>): void;
        abstract DelegationTotalRewards(call: grpc_1.ServerUnaryCall<QueryDelegationTotalRewardsRequest, QueryDelegationTotalRewardsResponse>, callback: grpc_1.sendUnaryData<QueryDelegationTotalRewardsResponse>): void;
        abstract DelegatorValidators(call: grpc_1.ServerUnaryCall<QueryDelegatorValidatorsRequest, QueryDelegatorValidatorsResponse>, callback: grpc_1.sendUnaryData<QueryDelegatorValidatorsResponse>): void;
        abstract DelegatorWithdrawAddress(call: grpc_1.ServerUnaryCall<QueryDelegatorWithdrawAddressRequest, QueryDelegatorWithdrawAddressResponse>, callback: grpc_1.sendUnaryData<QueryDelegatorWithdrawAddressResponse>): void;
        abstract CommunityPool(call: grpc_1.ServerUnaryCall<QueryCommunityPoolRequest, QueryCommunityPoolResponse>, callback: grpc_1.sendUnaryData<QueryCommunityPoolResponse>): void;
    }
    export class QueryClient extends grpc_1.makeGenericClientConstructor(UnimplementedQueryService.definition, "Query", {}) {
        constructor(address: string, credentials: grpc_1.ChannelCredentials, options?: Partial<grpc_1.ChannelOptions>) {
            super(address, credentials, options);
        }
        Params: GrpcUnaryServiceInterface<QueryParamsRequest, QueryParamsResponse> = (message: QueryParamsRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<QueryParamsResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<QueryParamsResponse>, callback?: grpc_1.requestCallback<QueryParamsResponse>): grpc_1.ClientUnaryCall => {
            return super.Params(message, metadata, options, callback);
        };
        ValidatorOutstandingRewards: GrpcUnaryServiceInterface<QueryValidatorOutstandingRewardsRequest, QueryValidatorOutstandingRewardsResponse> = (message: QueryValidatorOutstandingRewardsRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<QueryValidatorOutstandingRewardsResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<QueryValidatorOutstandingRewardsResponse>, callback?: grpc_1.requestCallback<QueryValidatorOutstandingRewardsResponse>): grpc_1.ClientUnaryCall => {
            return super.ValidatorOutstandingRewards(message, metadata, options, callback);
        };
        ValidatorCommission: GrpcUnaryServiceInterface<QueryValidatorCommissionRequest, QueryValidatorCommissionResponse> = (message: QueryValidatorCommissionRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<QueryValidatorCommissionResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<QueryValidatorCommissionResponse>, callback?: grpc_1.requestCallback<QueryValidatorCommissionResponse>): grpc_1.ClientUnaryCall => {
            return super.ValidatorCommission(message, metadata, options, callback);
        };
        ValidatorSlashes: GrpcUnaryServiceInterface<QueryValidatorSlashesRequest, QueryValidatorSlashesResponse> = (message: QueryValidatorSlashesRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<QueryValidatorSlashesResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<QueryValidatorSlashesResponse>, callback?: grpc_1.requestCallback<QueryValidatorSlashesResponse>): grpc_1.ClientUnaryCall => {
            return super.ValidatorSlashes(message, metadata, options, callback);
        };
        DelegationRewards: GrpcUnaryServiceInterface<QueryDelegationRewardsRequest, QueryDelegationRewardsResponse> = (message: QueryDelegationRewardsRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<QueryDelegationRewardsResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<QueryDelegationRewardsResponse>, callback?: grpc_1.requestCallback<QueryDelegationRewardsResponse>): grpc_1.ClientUnaryCall => {
            return super.DelegationRewards(message, metadata, options, callback);
        };
        DelegationTotalRewards: GrpcUnaryServiceInterface<QueryDelegationTotalRewardsRequest, QueryDelegationTotalRewardsResponse> = (message: QueryDelegationTotalRewardsRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<QueryDelegationTotalRewardsResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<QueryDelegationTotalRewardsResponse>, callback?: grpc_1.requestCallback<QueryDelegationTotalRewardsResponse>): grpc_1.ClientUnaryCall => {
            return super.DelegationTotalRewards(message, metadata, options, callback);
        };
        DelegatorValidators: GrpcUnaryServiceInterface<QueryDelegatorValidatorsRequest, QueryDelegatorValidatorsResponse> = (message: QueryDelegatorValidatorsRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<QueryDelegatorValidatorsResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<QueryDelegatorValidatorsResponse>, callback?: grpc_1.requestCallback<QueryDelegatorValidatorsResponse>): grpc_1.ClientUnaryCall => {
            return super.DelegatorValidators(message, metadata, options, callback);
        };
        DelegatorWithdrawAddress: GrpcUnaryServiceInterface<QueryDelegatorWithdrawAddressRequest, QueryDelegatorWithdrawAddressResponse> = (message: QueryDelegatorWithdrawAddressRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<QueryDelegatorWithdrawAddressResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<QueryDelegatorWithdrawAddressResponse>, callback?: grpc_1.requestCallback<QueryDelegatorWithdrawAddressResponse>): grpc_1.ClientUnaryCall => {
            return super.DelegatorWithdrawAddress(message, metadata, options, callback);
        };
        CommunityPool: GrpcUnaryServiceInterface<QueryCommunityPoolRequest, QueryCommunityPoolResponse> = (message: QueryCommunityPoolRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<QueryCommunityPoolResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<QueryCommunityPoolResponse>, callback?: grpc_1.requestCallback<QueryCommunityPoolResponse>): grpc_1.ClientUnaryCall => {
            return super.CommunityPool(message, metadata, options, callback);
        };
    }
}
